### ISSUE TITLE
Lockbox used in cocoa Mac app that did not ovverite my value for same key

### ISSUE THREAD

**Issue by nitingohel** [granoff/Lockbox#37]
i used Lockbox.h and Lockbox.m file in to my mac application for store user_id and session_id after logged in user. But that give me alwasy same id and session id after all i used another logged in id here following is my approach.

AFTER LOGIN:

              NSLog(@"==%@ and sessiong %@",[dict2 objectForKey:@"user_id"],[dict2 objectForKey:@"session_id"]);
                 
                 [Lockbox setString:[dict2 objectForKey:@"user_id"] forKey:@"user_id"];
                 [Lockbox setString:[dict2 objectForKey:@"session_id"] forKey:@"session_id"];
                 [Lockbox setString:[dict2 objectForKey:@"username"] forKey:@"username"];
                 [Lockbox setString:@"1" forKey:@"started"];
                 
                 
                  NSLog(@"==%@ and sessiong %@",[Lockbox stringForKey:@"user_id"],[Lockbox stringForKey:@"session_id"]);

i got always same NSLog of last printed:

and at logout time i set nil for each stored key:

    [Lockbox setString:nil forKey:@"user_id"];
    [Lockbox setString:nil forKey:@"session_id"];
    [Lockbox setString:nil forKey:@"LastCount"];
    [Lockbox setString:nil forKey:@"deviceToken"];
    [Lockbox setString:nil forKey:@"lastLoginEmail"];

So my question is that is there anything need to change while we use these class in cocoa mac application. Please help me for this issue

**Comment by granoff** [comment]
This library does not officially support Mac OS and Cocoa. See the _Requirements & Limitations_ section of the README.

I had hoped, at this point, that someone might have stepped up to fork the repo and add that support... But alas, no one has... yet. Sorry.
