### ISSUE TITLE
Remove UIKit import

### ISSUE THREAD

**Issue by nathanhosselton** [granoff/Lockbox#39]
A nit-pick perhaps, but this library doesn't utilize any part of UIKit so its inclusion is puzzling and seemingly unnecessary. Please correct me if I'm wrong though.

**Comment by granoff** [comment]
You're probably right. :-) Thanks for pointing this out.

**Comment by stannedelchev** [comment]
Just to test this, I removed all references of "UIKit" in the source code, but not the .pbxproj. 
Everything compiles, the unit tests run fine. 
The test app seems to be ok in the simulator, but I only did a few clicks.

The only place I didn't clean was the precompiled header in the app - ```LockBox/LockBox/LockBox-Prefix.pch``` 

If the ```#import <UIKit/UIKit.h>``` statement there is removed, the app doesn't compile (expectedly so).

We can either leave the import in the precompiled header, or have separate imports in each viewcontroller/appdelegate, etc.

**Comment by granoff** [comment]
I think the appropriate fix here is to remove the import of `UIKit.h` from `Lockbox.h`, but leave any `UIKit` references in files under `Lockbox/` unchanged. The latter is a sample project that does require UIKit. When incorporating Lockbox into your own project, you need only include `Lockbox.[hm]` there in. If Lockbox is incorporated via CocoaPods, this is what happens.

**Comment by nathanhosselton** [comment]
Apologies. Yes, I was speaking only to the import within the Lockbox header file.

**Comment by granoff** [comment]
Thanks!
