### ISSUE TITLE
Lockbox +setDictionary: converts `NSNumber` into `NSString`

### ISSUE THREAD

**Issue by hlung** [granoff/Lockbox#43]
Right now if you have a dictionary `{@"num": @123}`, and you save it into using `Lockbox +setDictionary:`.
After that if you retrieve it using `Lockbox +dictionaryForKey:`, you will get `{@"num": @"123"}`. Notice that what was `NSNumber` now an `NSString`.

This may be a limitation by iOS Keychain. But it would be better if the object saved in the dictionary was `NSNumber`, it should be retrieved back as `NSNumber` not `NSString`. Or if this is not possible, at least add a note about this limitation in a comment or something. :)

Thanks!

**Comment by granoff** [comment]
This is... unfortunate. This may be partially how the keychain works and partially how I implemented the various methods. But I would have expected basic data types like this to remain unchanged on retrieval. Looking at the code, a simple solution is not obvious without breaking previous versions. I'll have to think on it...

**Comment by granoff** [comment]
I have just pushed an update to Lockbox that deprecates all the `setXxx` and related getters, and added methods for archiving and unarchiving objects of any kind that conform to NSSecureCoding. This should solve this issue where retrieving complex objects stored using the old `setXxx` methods did not result in the same objects on the way out.
