### ISSUE TITLE
Cannot find interface declaration for 'NSObject', superclass of 'Lockbox'

### ISSUE THREAD

**Issue by mrzystem** [granoff/Lockbox#47]
When using only Lockbox.h and Lockbox.m in a project (instead of using CocoaPods or the example project) the above build error appears.

My suggestion is to include:

`#import <Foundation/Foundation.h>`

At the top of Lockbox.h.

**Comment by granoff** [comment]
Most projects, I think, would include `Foundation.h` from somewhere else, so including it via the Lockbox sources would be redundant (in the strictest sense). It's not that big a deal to include it in your project yourself, is it?

**Comment by mrzystem** [comment]
True, but it seems good programming practice (according to me :) ) to make a class compile and work independently of the rest of the project, considering the rest of the project is a black box.

**Comment by granoff** [comment]
Hmm... Well, I suppose I can't hurt. If you want to create a pull request that adds the import to Lockbox.h, go ahead.
