### ISSUE TITLE
Wiping Clean Keychain Keys

### ISSUE THREAD

**Issue by marcelosalloum** [granoff/Lockbox#49]
Hey guys,

My app started prompting an error message for duplicate keys in the keychain [error -25299]:

```
CKLs-iPhone-5S securityd[78] : securityd_xpc_dictionary_handler MyApp[2571] add The operation couldn’t be completed. (OSStatus error -25299 - duplicate item O,genp,E99372E2,L,ck,XYZ6M5UYJ9.com.mydomain.myapp,0,acct,svce,v_Data,20151218165347.298588Z,2CAE5650)

CKLs-iPhone-5S MyApp[2571] : SecOSStatusWith error:[-25299] The operation couldn’t be completed. (OSStatus error -25299 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -25299 - duplicate item O,genp,E99372E2,L,ck,XYZ6M5UYJ9.com.mydomain.myapp,0,acct,svce,v_Data,20151218165347.298588Z,2CAE5650))
```

I couldn't solve it by using the `initWithKeyPrefix` method, although overriding the `_defaultKeyPrefix` value within the `initialize` method solved the problem.

I'd like to know if there is a way to manually clean all keys stored by Lockbox. I imagine this is an issue with the Keychain rather than Lockbox.

**Comment by granoff** [comment]
You'd have to know all the keys you stored using Lockbox to then be able to remove them all.

Based on your description this does sound like more of a generic Keychain issue though.

**Comment by marcelosalloum** [comment]
You're righit @granoff. Thanks
