### ISSUE TITLE
Migration to archiveObject

### ISSUE THREAD

**Issue by winzig** [granoff/Lockbox#50]
I don't see anything in the readme to guide on migration to the new archiveObject and unarchiveObjectForKey methods, so I assumed it was just straightforward change to the name of the method being called, perhaps with casting as needed. Yet after doing this, I'm running into this error when trying to run my app on a device that had previously used the set* commands of the previous version:

    2016-02-10 16:24:59.504 iATN[3326:539804] *** Terminating app due to uncaught exception   
    'NSInvalidArgumentException', reason: '*** -[NSKeyedUnarchiver initForReadingWithData:]: 
    incomprehensible archive (0x50, 0x57, 0x3d, 0x25, 0x62, 0x61, 0x42, 0x25)'
    *** First throw call stack:
    (0x2b493f8f 0x39b44c8b 0x2b493ed5 0x2c165315 0xac2cc9 0xac3b87 0x16ae90 0x170710 0x16a818 0x16bedc 0x16c21c 0x140514 0x142800 0x2eb810b3 0x2ed77929 0x2ed79fe9 0x2ed84c69 0x2ed7878b 0x3207aec9 0x2b459db5 0x2b459079 0x2b457bb3 0x2b3a3f31 0x2b3a3d43 0x2eb7ac87 0x2eb75879 0x152e84 0x3a0f6aaf)
    libc++abi.dylib: terminating with uncaught exception of type NSException

Is there more to the migration than just changing the methods being called, and casting as appropriate?

In my case I was doing some array and string storage with the previous version, in a Swift app.

**Comment by winzig** [comment]
Specifically the code that is crashing went from:

    if let myArray = Lockbox.arrayForKey("MyArray") as? [String] {

to:

    if let myArray = Lockbox.unarchiveObjectForKey("MyArray") as? [String] {

The value was originally stored in the app in the previous version using:

    Lockbox.setArray(myArray, forKey: "MyArray", accessibility: kSecAttrAccessibleAfterFirstUnlock)

**Comment by granoff** [comment]
There is no automatic migration from the old `setXxx` methods to the new archive/unarchive methods. In fact, that would be nearly impossible as there is no way to know what you stored for any given key. I will update the README with some guidance.

To migrate, you would need to fetch your data using the now deprecated type-specific methods, and then store them again using the new `archiveObjectForKey:` method.

I can imagine that you might do this at launch, one time, for all your Lockbox data stored using the old methods. Then make a note by storing another key, either via Lockbox or in User Defaults or somewhere else, that you've done this migration in your app. So on subsequent launches, you wouldn't have to do the migration again. In fact, that would be redundant and probably mess up your data.

Sorry for the inconvenience.

**Comment by winzig** [comment]
Is the benefit in moving to this just reduced complexity for new code? It seems like for existing apps it may be better to just continue with the older version, rather than adding migration code to our codebase for all time. But maybe I'm not fully understanding the benefits.

**Comment by granoff** [comment]
The original implementation (all the type-specific `setXxx` methods) is limited, it turns out, if you want to store a complex object. For example, an array of strings can be stored and retrieved easily enough. But an array of arrays not so much; the retrieved array's contents were not arrays.

The new model stores opaque data from a keyed archive, relying on each core object to serialize and de-serialize itself on its way into and out of a keyed archive, respectively. So this allows you to store any complex object provided the object (and any contained objects) conform to `NSSecureCoding`. It is more robust, and removes the burden of worrying about data types from Lockbox.

**Comment by winzig** [comment]
OK, great, thank you!
