### ISSUE TITLE
Sharing keys with iOS Today Widget

### ISSUE THREAD

**Issue by marcelosalloum** [granoff/Lockbox#51]
Hi guys,

is that possible to share the lockbox instance and it's data between multiple targets, where one of them is an iOS Widget?

Thanks

**Comment by granoff** [comment]
Without having looked at the details, I think the answer is Yes. You have to setup your project to allow for keychain sharing and you would likely need to give Lockbox a specific identifier to use so its stored values wind up in the right place.

**Comment by marcelosalloum** [comment]
I followed [this tutorial](http://useyourloaf.com/blog/keychain-group-access/) and managed to do it.
