### ISSUE TITLE
Exception thrown when unarchiveObjectForKey called on ios 8

### ISSUE THREAD

**Issue by ninjitaru** [granoff/Lockbox#52]
Hi,

I have notice that because the use of` [[NSKeyedUnarchiver alloc] initForReadingWithData:data]`,
It will throw NSInvalidArgumentException
[NSKeyedUnarchiver initForReadingWithData:]: incomprehensible archive (xxx,xxx,xxx,0x0, 0x0, 0x0, 0x0, 0x0)

This only happens on ios8 ... it won't happen on ios9 ...
but It think it might be safer to catch the exception within `unarchiveObjectForKey`.. so ppl using this library won't have unexpected exception happen to them
Thanks

**Comment by granoff** [comment]
At the risk of stating the obvious, you cannot mix the new Lockbox v3 APIs with data stored using pre-v3 APIs. That is to say, if you had stored a string using `-setString:forKey:` you cannot then use `-unarchiveObjectForKey:` to retrieve it. You would see the behavior you describe (or worse). I can't imagine this scenario would work on any version of iOS, so your last comment about it working on iOS9 is perplexing. Can you share some code so I can see what you're actually doing?

**Comment by granoff** [comment]
Your use of both the v2 and v3 APIs to first fetch, and then store, a value for a key is correct. What i meant by not mixing was that you cannot store a key using a v2 API and then retrieve it properly using a v3 API. Your migration code, which fetches then stores, is fine.

I see what you're saying about catching the error. I'll look into it.

**Comment by marcelosalloum** [comment]
Hey @granoff, any hints when v 3.0.1 will be available in Cocoapods?

**Comment by granoff** [comment]
Hm. Thought it would be by now. The tags are there, the podspec seems right. Investigating...

**Comment by granoff** [comment]
Available now. Sorry!

**Comment by marcelosalloum** [comment]
Thanks a lot!
