### ISSUE TITLE
How to save NSData in Dictionary format

### ISSUE THREAD

**Issue by jasper-chan** [granoff/Lockbox#53]
Hello,
I have been using your project for a long time now and I really like the simplicity it provides to using keychains safely. However, I was curious to know how one would save NSData into a NSMutableDictionary, and saving that dictionary into the keychain using Lockbox?

My scenario is as follows:
1) I'm using Realm (https://realm.io/) with encryption for my persistent data storage, and would like to store the key in the keychain using Lockbox
2) Realm has a strict requirement that the key be exactly 64 bytes long. 
3) The password is to be stored inside a NSMutableDictionary, which is persisted in the keychain via Lockbox. This is because our platform can be used by multiple users, and we want to keep user details grouped up together via using a dictionary

I'm noticing that when I retrieve the value from Lockbox, the value is a NSString, and is also much longer in length. If memory serves correctly, a 64 byte length NSData became 160+ byte length NSString.

Thanks

**Comment by granoff** [comment]
I would suggest using the Lockbox v3 APIs, which allow you to store whatever kind of object you want to, as long it conforms to `NSSecureCoding`. One of the reasons behind developing the v3 APIs was that the now-deprecated original APIs can sometimes have trouble with complex data structures like dictionaries.

**Comment by jasper-chan** [comment]
Hello @granoff 
Thank you very much for your recommendation. It solved my problem flawlessly :)
