### ISSUE TITLE
LockBox doesn't save info in xcode 8

### ISSUE THREAD

**Issue by alexeybolv** [granoff/Lockbox#55]
`[Lockbox archiveObject:self.passwordTextField.text forKey:kPassword];
  [Lockbox archiveObject:self.numberTextField.text forKey:kPhone];`

When i try to unarchive it returns nil in simulator, but on the real device it works.
In Xcode 7 it works perfect.

**Comment by hannseman** [comment]
Enabling Keychain sharing appears to fix this issue for some reason.

**Comment by granoff** [comment]
Thanks @hannseman ! 

@alexeybolv : What version of iOS was on your device at the time?

I think it is unfortunate that Keychain Sharing must be enabled _just to store something in your own keychain_ especially if you have no intention of sharing your keychain. I think a little more investigation is required, perhaps.

**Comment by alexeybolv** [comment]
iOS version is 10.0

**Comment by granoff** [comment]
@alexeybolv: I figured as much.

Well, enabling Keychain Sharing seems to be the quick fix, at least. It may be _the_ fix, which seems like an awfully big hammer to me, at the moment.

We'll leave this issue open for the time being as a reminder.

**Comment by granoff** [comment]
When you enable Keychain Sharing, as I did in the Lockbox project, Xcode adds a keychain group. I tried removing that group from the list of enabled groups while keeping Keychain Sharing enabled. The unit tests passed.

It would be nice if there was a way to have the entitlements set properly when the Lockbox cocoapod is installed, but I don't think there's a way to do that. Documentation will have to suffice, I think.

**Comment by granoff** [comment]
I've pushed the changes I made earlier which include:
# Enabled Keychain Sharing in the sample project, but removed the keychain group that Xcode added to the list of keychain groups. It's not needed (especially because we're not sharing, by default), but the entitlement is apparently needed to access the keychain, whether you're sharing it or not.
# Updated the README
# Bumped the version to 3.0.2

There are no functional changes to Lockbox itself.

**Comment by iwasrobbed** [comment]
Seems like a radar should be filed for this; no reason to share the keychain if you only have one app accessing it.
