### ISSUE TITLE
Upgrading from Swift 2.3 -> 3 leaves old values inaccessible.

### ISSUE THREAD

**Issue by Menthuss** [granoff/Lockbox#58]
I'm running into an unfortunate issue after upgrading from Swift 2.3 to Swift 3. I was initially using Lockbox 1.4.9 to store important values in Keychain. Now that I've upgraded to Swift 3 and updated Lockbox's methods (changing stringForKey to string(forKey:) ), I can't seem to access the stored values anymore as they all return nil. They're still in the keychain as I can still access them when I install the Swift 2.3 version of my app. 

What's my best course of action here?

**Comment by granoff** [comment]
Had you been using the Lockbox 3 archiveObject methods at all? The deprecated Lockbox 2 setXxx methods and the newer archiveObject methods are incompatible. That is you cannot use setString and unarchiveObject together. The only way to migrate from Lockbox 2 to Lockbox 3 is to use getString and then archiveObject, and then unarchiveObject will work. I only mention this for clarity, as it sounds like you have only been using the set/get methods.

For what it's worth, I wrote a new library named Strongbox (see README for a reference) that implements Lockbox3 in Swift. Not sure that is going to help here, but wanted to mention it.

I think I am going to need to see how you are storing and retrieving your objects to be more helpful.

**Comment by Menthuss** [comment]
I've only used 1.4.9 for both Swift 2.3 and 3.

To give you an example, I'm storing and retrieving the user's authentication token in Lockbox like so:

In Swift 2.3:
`Lockbox.setString(authToken, forKey: Constants.KEY_AUTH_TOKEN)`
`Lockbox.stringForKey(Constants.KEY_AUTH_TOKEN)`
In Swift 3:
`Lockbox.setString(authToken, forKey: Constants.KEY_AUTH_TOKEN)`
`Lockbox.string(forKey: Constants.KEY_AUTH_TOKEN)`

The problem is that all of my keys return nil in the Swift 3 version of my app, which means that all of the user's settings are gone. I'm guessing the underlying logic in how Lockbox interacts with Keychain changed in Swift 3 and therefore, Lockbox can't find the old associated values anymore.

**Comment by granoff** [comment]
I bet if you were to step into the call to string(forKey:...) you would discover what is really going on. Can you help me out and do that? My guess would be an error is occurring, so Lockbox is returning nil, but the error would be most helpful to know!

**Comment by Menthuss** [comment]
I've stepped through the code and if I'm reading this right, Keychain is returning a `errSecItemNotFound` error when trying to look for they associated value. 

`CFDataRef data = nil;
    OSStatus status =
    SecItemCopyMatching ( (LOCKBOX_DICTREF) query, (CFTypeRef *) &data );
    if (status != errSecSuccess && status != errSecItemNotFound)
        DLog(@"SecItemCopyMatching failed for key %@: %d", hierKey, (int)status);`

**Comment by granoff** [comment]
That nuance of they keychain, using Lockbox rather than Strongbox, may be an oddity of the bridging that is happening between Objective-C and Swift. Weird and not what what I would have expected. Thanks for the providing the details.

If you want to stick with Lockbox, I would at least try the latest version; v1.4.9 is pretty old.

To get around the minimum deployment target of Strongbox, to at least try it, you could fork the repo and make the necessary changes to see if it helps. Strongbox does not have Lockbox's setXxx/getXxx methods, however.

**Comment by Menthuss** [comment]
Well, I've managed to implement Lockbox v3 in my project... mostly. I've written a function that migrates the old values to the archiveObject functions. I'm running into an odd issue though: the stored values seem to be getting reset when the app enters the background. Am I missing some sort of saveValues call?

**Comment by granoff** [comment]
Great news! Thanks for the update. Sorry for the confusion on this. Certainly the weird behavior of the keychain is a little concerning, but I am glad that an included API solved the problem for you.
