### ISSUE TITLE
Better way to save serialize NSDictionary, NSArray to the Keychain, and also support NSData

### ISSUE THREAD

**Issue by rivera-ernesto** [granoff/Lockbox#6]
Instead of using the fixed kDelimeter property list serialization could be used which would be more robust and also provide more complex object trees.

http://stackoverflow.com/questions/9948698/store-nsdictionary-in-keychain

**Comment by granoff** [comment]
I have just pushed an update to Lockbox that deprecates all the setXxx and related getters, and added methods for archiving and unarchiving objects of any kind that conform to NSSecureCoding.
