### ISSUE TITLE
podspec does not define minimum iOS version

### ISSUE THREAD

**Issue by jmfriend** [granoff/Lockbox#60]
The podspec for Lockbox does not state a minimum iOS version. The impact of this appears to be that the system assumes it's been compiled just for the latest version of iOS. This generates this warning: 

ld: warning: object file (.../Build/Products/Debug-iphoneos/Lockbox/libLockbox.a(Lockbox-dummy.o)) was built for newer iOS version (11.2) than being linked (9.0)

**Comment by granoff** [comment]
Look for v3.0.5 with a fix that explicitly specifies an iOS target. Just published. Let me know if that does the trick.

**Comment by jmfriend** [comment]
Fab. Sorted the issue! Many thanks
