### ISSUE TITLE
Still can delete data, with "Keychain Access.app"

### ISSUE THREAD

**Issue by WestleyR** [granoff/Lockbox#64]
Using the builtin app on macOS (Keychain Access.app), it is possible delete the saved data. Is there a way to make it undeletable?

**Comment by granoff** [comment]
I suppose there might be a way to add some additional attributes to the saved data that might, say, require a password to be able to delete it that way. But I'm not sure at the moment.

That being said, Lockbox was not designed for macOS. Only iOS/iPadOS.

**Comment by WestleyR** [comment]
Hmm, I did some research and was unable to find any information on making it undeleteable. Although with the Keychain Access app, I seem to be able to delete all the keys there (though not tested lol). I'm sure if there is even any way to store undeletable (only app write access) data... let me know if you have any idea... Thanks for your help!
